import type { Company } from "@/types/company";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Coinbase",
    sector: "Crypto / Fintech",
    description: "Digital currency exchange platform",
    summary: "Coinbase reported strong Q4 earnings driven by renewed crypto trading volume. The company is expanding its institutional custody services and recently launched a new Layer 2 blockchain network. Regulatory clarity in the US has boosted investor confidence.",
    newsArticles: [
      {
        id: "n1",
        title: "Coinbase Q4 Revenue Surges 150% on Crypto Rally",
        source: "Bloomberg",
        url: "#",
        publishedAt: "2026-03-08T09:30:00Z",
        signal: "positive",
        isBreaking: true,
        summary: "Coinbase beat analyst expectations with Q4 revenue up 150% YoY, driven by a surge in retail and institutional crypto trading volumes following Bitcoin's rally past $100K.",
        tags: ["earnings", "crypto", "revenue"],
      },
      {
        id: "n2",
        title: "Coinbase Expands Institutional Custody to Asia-Pacific",
        source: "CoinDesk",
        url: "#",
        publishedAt: "2026-03-07T14:00:00Z",
        signal: "positive",
        summary: "The exchange is opening custody operations in Singapore and Hong Kong, targeting $50B+ in institutional assets under management by year-end.",
        tags: ["expansion", "institutional", "asia"],
      },
      {
        id: "n3",
        title: "Base Network Hits 10M Daily Transactions Milestone",
        source: "The Block",
        url: "#",
        publishedAt: "2026-03-06T11:00:00Z",
        signal: "positive",
        summary: "Coinbase's Layer 2 network Base has become the second-largest L2 by transaction volume, surpassing Arbitrum for the first time.",
        tags: ["base", "L2", "blockchain"],
      },
      {
        id: "n4",
        title: "SEC Drops Remaining Enforcement Action Against Coinbase",
        source: "Reuters",
        url: "#",
        publishedAt: "2026-03-05T16:30:00Z",
        signal: "positive",
        summary: "The SEC officially dismissed its lawsuit against Coinbase, ending a 3-year legal battle. This removes a major regulatory overhang and clears the path for new product launches.",
        tags: ["regulation", "SEC", "legal"],
      },
      {
        id: "n5",
        title: "Coinbase Faces Growing Competition from Kraken in EU Markets",
        source: "Financial Times",
        url: "#",
        publishedAt: "2026-03-03T08:00:00Z",
        signal: "negative",
        summary: "Kraken has captured 35% of the EU crypto exchange market, up from 18% a year ago. Coinbase's European market share declined to 22% amid aggressive Kraken pricing.",
        tags: ["competition", "EU", "market-share"],
      },
    ],
    lastUpdated: "2026-03-08T10:00:00Z",
  },
  {
    id: "2",
    name: "Instacart",
    sector: "E-commerce / Delivery",
    description: "Online grocery delivery and pickup service",
    summary: "Instacart continues to grow its advertising business, now accounting for 30% of revenue. The company announced a partnership with major retail chains to expand same-day delivery coverage nationwide.",
    newsArticles: [
      {
        id: "n6",
        title: "Instacart Ad Revenue Hits Record $1.2B Annual Run Rate",
        source: "TechCrunch",
        url: "#",
        publishedAt: "2026-03-07T12:00:00Z",
        signal: "positive",
        summary: "Instacart's advertising platform now generates $1.2B ARR, making it the third-largest retail media network in the US after Amazon and Walmart.",
        tags: ["advertising", "revenue", "retail-media"],
      },
      {
        id: "n7",
        title: "Instacart Partners with Costco for Nationwide Same-Day Delivery",
        source: "Reuters",
        url: "#",
        publishedAt: "2026-03-06T09:00:00Z",
        signal: "positive",
        summary: "The Costco partnership adds 600+ warehouse locations to Instacart's same-day delivery network, potentially reaching 95% of US households.",
        tags: ["partnership", "expansion", "delivery"],
      },
      {
        id: "n8",
        title: "Instacart Stock Slides 5% After Analyst Downgrade",
        source: "CNBC",
        url: "#",
        publishedAt: "2026-03-04T15:30:00Z",
        signal: "negative",
        summary: "Morgan Stanley downgraded Instacart to 'equal-weight' citing concerns about grocery delivery margin compression and increased competition from DoorDash and Uber Eats.",
        tags: ["stock", "downgrade", "analyst"],
      },
    ],
    lastUpdated: "2026-03-07T14:00:00Z",
  },
  {
    id: "3",
    name: "Flexport",
    sector: "Logistics / Supply Chain",
    description: "Technology-driven freight forwarding and customs brokerage",
    summary: "Flexport is leveraging AI to optimize shipping routes and reduce costs by 15%. The company recently secured a major contract with a Fortune 100 retailer for end-to-end supply chain management.",
    newsArticles: [
      {
        id: "n9",
        title: "Flexport's AI Route Optimization Saves Clients $200M Annually",
        source: "WSJ",
        url: "#",
        publishedAt: "2026-03-08T07:00:00Z",
        signal: "positive",
        isBreaking: true,
        summary: "Flexport's new AI-powered routing engine reduced average shipping times by 18% and costs by 15% across its network, saving enterprise clients a combined $200M annually.",
        tags: ["AI", "logistics", "cost-savings"],
      },
      {
        id: "n10",
        title: "Flexport Wins Fortune 100 End-to-End Supply Chain Deal",
        source: "Forbes",
        url: "#",
        publishedAt: "2026-03-06T10:00:00Z",
        signal: "positive",
        summary: "An undisclosed Fortune 100 retailer has signed a multi-year contract for Flexport to manage its entire supply chain, from factory floor to last-mile delivery.",
        tags: ["enterprise", "contract", "supply-chain"],
      },
      {
        id: "n11",
        title: "Global Shipping Delays Impact Flexport Q1 Outlook",
        source: "Bloomberg",
        url: "#",
        publishedAt: "2026-03-02T13:00:00Z",
        signal: "negative",
        summary: "Red Sea shipping disruptions and port congestion in Southeast Asia are expected to impact Flexport's Q1 margins, though the company says its AI routing partially mitigates delays.",
        tags: ["shipping", "delays", "risk"],
      },
    ],
    lastUpdated: "2026-03-08T08:00:00Z",
  },
  {
    id: "4",
    name: "Rippling",
    sector: "HR / Enterprise Software",
    description: "Unified workforce management platform",
    summary: "Rippling crossed $350M ARR and is rapidly expanding internationally. Their new IT management module has been adopted by over 2,000 companies since launch. The company is eyeing a potential IPO in late 2026.",
    newsArticles: [
      {
        id: "n12",
        title: "Rippling Valued at $13.5B in Latest Funding Round",
        source: "Bloomberg",
        url: "#",
        publishedAt: "2026-03-08T06:00:00Z",
        signal: "positive",
        isBreaking: true,
        summary: "Rippling raised $500M at a $13.5B valuation, making it one of the most valuable HR tech companies globally. The round was led by Coatue with participation from Founders Fund.",
        tags: ["funding", "valuation", "growth"],
      },
      {
        id: "n13",
        title: "Rippling Launches Operations in 12 New Countries",
        source: "TechCrunch",
        url: "#",
        publishedAt: "2026-03-07T09:00:00Z",
        signal: "positive",
        summary: "The expansion covers key markets in Europe and APAC, allowing companies to manage payroll, benefits, and compliance for employees in 50+ countries from a single platform.",
        tags: ["expansion", "international", "payroll"],
      },
      {
        id: "n14",
        title: "Rippling IT Module Sees 200% Adoption Growth",
        source: "VentureBeat",
        url: "#",
        publishedAt: "2026-03-05T11:00:00Z",
        signal: "positive",
        summary: "Over 2,000 companies adopted Rippling's IT management module since its launch, handling device management, app provisioning, and security policies from the unified platform.",
        tags: ["IT", "adoption", "product"],
      },
      {
        id: "n15",
        title: "Rippling Eyes Late 2026 IPO, Sources Say",
        source: "The Information",
        url: "#",
        publishedAt: "2026-03-03T14:00:00Z",
        signal: "neutral",
        summary: "Multiple sources indicate Rippling is in early conversations with investment banks about a potential IPO in Q4 2026, though no formal process has begun.",
        tags: ["IPO", "public-markets"],
      },
    ],
    lastUpdated: "2026-03-08T09:00:00Z",
  },
  {
    id: "5",
    name: "Cruise",
    sector: "Autonomous Vehicles",
    description: "Self-driving car technology company",
    summary: "Cruise has resumed limited autonomous operations in select cities following regulatory approval. The company unveiled its next-generation vehicle platform designed for commercial deployment at scale.",
    newsArticles: [
      {
        id: "n16",
        title: "Cruise Resumes Autonomous Operations in Phoenix and Austin",
        source: "The Verge",
        url: "#",
        publishedAt: "2026-03-07T10:00:00Z",
        signal: "positive",
        summary: "After a 6-month operational pause, Cruise received regulatory approval to resume autonomous rides in Phoenix and Austin, initially operating with safety drivers during daytime hours.",
        tags: ["autonomous", "operations", "regulation"],
      },
      {
        id: "n17",
        title: "Cruise Faces Renewed Scrutiny from California DMV",
        source: "WSJ",
        url: "#",
        publishedAt: "2026-03-04T08:00:00Z",
        signal: "negative",
        summary: "The California DMV has opened a new investigation into Cruise's incident reporting practices, potentially delaying the company's plans to resume San Francisco operations.",
        tags: ["regulation", "investigation", "risk"],
      },
    ],
    lastUpdated: "2026-03-07T12:00:00Z",
  },
  {
    id: "6",
    name: "Envoy",
    sector: "Workplace Technology",
    description: "Modern workplace platform for visitor management",
    summary: "Envoy's workplace platform now manages over 100,000 office locations globally. The company launched new AI-powered space planning features that have driven a 40% increase in enterprise contracts.",
    newsArticles: [
      {
        id: "n18",
        title: "Envoy Surpasses 100K Managed Office Locations Worldwide",
        source: "Fast Company",
        url: "#",
        publishedAt: "2026-03-06T08:00:00Z",
        signal: "positive",
        summary: "Envoy's platform now manages 100,000+ office locations across 120 countries, processing over 2M daily check-ins. The milestone makes Envoy the largest workplace management platform globally.",
        tags: ["milestone", "growth", "workplace"],
      },
      {
        id: "n19",
        title: "Envoy Launches AI-Powered Space Planning Tool",
        source: "Built In",
        url: "#",
        publishedAt: "2026-03-04T10:00:00Z",
        signal: "neutral",
        summary: "The new tool uses occupancy data and employee preferences to automatically optimize office layouts, desk assignments, and meeting room allocation, reducing real estate costs by up to 20%.",
        tags: ["AI", "product", "space-planning"],
      },
    ],
    lastUpdated: "2026-03-07T08:00:00Z",
  },
];
